version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: smartorder-app
        container_name: smartorder-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        ports:
            - "8000:8000"
        depends_on:
            - db
        networks:
            - smartorder-network
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=base64:YOUR_APP_KEY
            - DB_CONNECTION=pgsql
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=smartorder
            - DB_USERNAME=postgres
            - DB_PASSWORD=password
        command: php artisan serve --host=0.0.0.0 --port=8000

    db:
        image: postgres:16
        container_name: smartorder-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: smartorder
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - smartorder-network

    swagger-ui:
        image: swaggerapi/swagger-ui
        container_name: smartorder-swagger
        ports:
            - "8080:8080"
        environment:
            SWAGGER_JSON: /usr/share/nginx/html/docs/api-spec.yaml
        volumes:
            - ./docs:/usr/share/nginx/html/docs
        networks:
            - smartorder-network

networks:
    smartorder-network:
        driver: bridge

volumes:
    db-data:
