openapi: 3.0.3
info:
    title: SmartOrder API
    version: 1.0.0
    description: SmartOrder の注文 API ドキュメント

servers:
    - url: http://localhost:8000/api
      description: ローカル開発環境

paths:
    /orders:
        get:
            summary: 注文一覧を取得
            tags:
                - Orders
            responses:
                "200":
                    description: 正常に取得
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/Order"
        post:
            summary: 新しい注文を作成
            tags:
                - Orders
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/OrderRequest"
            responses:
                "201":
                    description: 作成成功
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Order"
                "400":
                    description: リクエストエラー
                "422":
                    description: バリデーションエラー
                "500":
                    description: サーバーエラー

components:
    schemas:
        Order:
            type: object
            properties:
                id:
                    type: integer
                customerName:
                    type: string
                product:
                    type: string
                quantity:
                    type: integer
                price:
                    type: number
                    format: float
                createdAt:
                    type: string
                    format: date-time
                updatedAt:
                    type: string
                    format: date-time
        OrderRequest:
            type: object
            required:
                - customerName
                - product
                - quantity
                - price
            properties:
                customerName:
                    type: string
                product:
                    type: string
                quantity:
                    type: integer
                    minimum: 1
                price:
                    type: number
                    format: float
                    minimum: 0
