openapi: 3.0.3
info:
    title: SmartOrder API
    description: SmartOrder - B2B 受発注クラウドサービスの API 仕様書
    version: 1.0.0
servers:
    - url: http://localhost:8000/api
      description: ローカル開発環境
    - url: https://api.smartorder.example.com
      description: 本番環境

paths:
    /orders:
        get:
            summary: 注文一覧を取得する
            tags:
                - Orders
            responses:
                "200":
                    description: 成功
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/Order"
        post:
            summary: 新しい注文を作成する
            tags:
                - Orders
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/NewOrder"
            responses:
                "201":
                    description: 作成成功
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Order"

    /orders/{orderId}:
        get:
            summary: 注文詳細を取得する
            tags:
                - Orders
            parameters:
                - name: orderId
                  in: path
                  required: true
                  schema:
                      type: string
            responses:
                "200":
                    description: 成功
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Order"

components:
    schemas:
        Order:
            type: object
            properties:
                id:
                    type: string
                customerName:
                    type: string
                product:
                    type: string
                quantity:
                    type: integer
                price:
                    type: number
                status:
                    type: string
                    enum:
                        - pending
                        - confirmed
                        - shipped
                        - completed
                createdAt:
                    type: string
                    format: date-time
                updatedAt:
                    type: string
                    format: date-time

        NewOrder:
            type: object
            required:
                - customerName
                - product
                - quantity
                - price
            properties:
                customerName:
                    type: string
                product:
                    type: string
                quantity:
                    type: integer
                price:
                    type: number
